# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/saadwaheed/Desktop/10x/trainings/TCPs/c6/gpio-v2.0/gpio/axi_gpio_0/axi_gpio_0.xci
# IP: The module: 'axi_gpio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/saadwaheed/Desktop/10x/trainings/TCPs/c6/gpio-v2.0/gpio/axi_gpio_0/axi_gpio_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/saadwaheed/Desktop/10x/trainings/TCPs/c6/gpio-v2.0/gpio/axi_gpio_0/axi_gpio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/saadwaheed/Desktop/10x/trainings/TCPs/c6/gpio-v2.0/gpio/axi_gpio_0/axi_gpio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/saadwaheed/Desktop/10x/trainings/TCPs/c6/gpio-v2.0/gpio/axi_gpio_0/axi_gpio_0.xci
# IP: The module: 'axi_gpio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/saadwaheed/Desktop/10x/trainings/TCPs/c6/gpio-v2.0/gpio/axi_gpio_0/axi_gpio_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/saadwaheed/Desktop/10x/trainings/TCPs/c6/gpio-v2.0/gpio/axi_gpio_0/axi_gpio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/saadwaheed/Desktop/10x/trainings/TCPs/c6/gpio-v2.0/gpio/axi_gpio_0/axi_gpio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
